language: java
install: mvn install -DskipTests -Dgpg.skip
jdk:
- oraclejdk9
sudo: false
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
addons:
  sonarcloud:
    organization: bingoohuang-github
    token:
      secure: Q0b81ebLGrl8/lhQVwnPz+yOWMYqsI3QK4PjwPT8GPmbA47cs8oHiZDTm40mAb5lUvd1jkcMhmnG35ywIKoQswnkvCJdSYfSdmajXVALKB5I6sVSILec3TtZVfzahIScXi3C0wvUg8X0av9bj7L5qqi76sxGfAeSw/qp9/HCHtnB/H/98LIoCqf5pfqaSfGQP0i7JRq99U/9hFSdQ4cXJi7P1OD3LTcvfCL83XGSVoWydh8eSVDqRzsV7zZEPPpE7MNoMCgwot3SJashK7zYaMIU+9ML1mW31ncujHkF+zIBEELtU9aaymhPZSqeAqtTT+JCBdq8tgEx3Ikt2dWs38iq9bSaIP3bLMRpfEEh1ylBo6+eo8Oq3aVnfzWvdYfehcEKftUj3ePSBbO+CMWFddWOeFd7GWCBSE4RDE2tsvyBdefbsH0Nm5fy4U7HgEWMvzVz5FQTUIFvxgW67gL9U/HFBlPQfH1+oVV3+sbCpxv/jbAHiqMkB7UKNV6i+2mTpQH180JTO36J3fvKOKHPhRmvZ+AmbT5ehXrlb9qk7xZvEsXK5JogXYRX5bYB5Vqd+IJLFx5BFxkZoftgH2wz9ZpwBi090lOJrPq+sjW8qCpBS/lqvap4Y6ZoeQLg7sjmTIqLb4CN4EGlf39Z0YREfyXLxlcnbmajOhgly+X4hhE=
script:
- mvn clean test jacoco:report coveralls:report install sonar:sonar -Dgpg.skip -Dsonar.organization=bingoohuang-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=a7fe683637d6e1f54e194817cc36e78936d4fe61
